"""Create core tables

Revision ID: ce9b6d9b4750
Revises: 
Create Date: 2026-04-02 10:23:07.841270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9b6d9b4750'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('waste_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('weight_estimate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'COMPLETED', 'CANCELLED', name='pickup_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PENDING', 'PAID', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('payment_ref', sa.String(length=255), nullable=True),
    sa.Column('collector_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications', sa.Column('pickup_id', sa.String(length=36), nullable=True))
    op.add_column('notifications', sa.Column('complaint_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    op.drop_column('notifications', 'complaint_id')
    op.drop_column('notifications', 'pickup_id')
    op.drop_table('pickups')
    # ### end Alembic commands ###
